// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FieldDrawer: typeof import('./src/components/FieldDrawer.vue')['default']
    FieldList: typeof import('./src/components/FieldList.vue')['default']
    FieldsCode: typeof import('./src/components/FieldsCode.vue')['default']
    FieldsContainer: typeof import('./src/components/FieldsContainer.vue')['default']
    FieldsPreview: typeof import('./src/components/FieldsPreview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Search.vue')['default']
    SearchItem: typeof import('./src/components/SearchItem.vue')['default']
  }
}

export {}
