// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ADescriptions: typeof import('ant-design-vue/es')['Descriptions']
    ADescriptionsItem: typeof import('ant-design-vue/es')['DescriptionsItem']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputGroup: typeof import('ant-design-vue/es')['InputGroup']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    ARadioButton: typeof import('ant-design-vue/es')['RadioButton']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    CodeSandboxOutlined: typeof import('@ant-design/icons-vue')['CodeSandboxOutlined']
    EditFilled: typeof import('@ant-design/icons-vue')['EditFilled']
    EyeOutlined: typeof import('@ant-design/icons-vue')['EyeOutlined']
    FieldDrawer: typeof import('./src/components/FieldDrawer.vue')['default']
    FieldList: typeof import('./src/components/FieldList.vue')['default']
    FieldNumberOutlined: typeof import('@ant-design/icons-vue')['FieldNumberOutlined']
    FieldsCode: typeof import('./src/components/FieldsCode.vue')['default']
    FieldsContainer: typeof import('./src/components/FieldsContainer.vue')['default']
    FieldsPreview: typeof import('./src/components/FieldsPreview.vue')['default']
    FieldStringOutlined: typeof import('@ant-design/icons-vue')['FieldStringOutlined']
    HolderOutlined: typeof import('@ant-design/icons-vue')['HolderOutlined']
    PlusOutlined: typeof import('@ant-design/icons-vue')['PlusOutlined']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Search.vue')['default']
    SearchItem: typeof import('./src/components/SearchItem.vue')['default']
  }
}

export {}
